# -*- coding: utf-8 -*-
"""stocks_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyTHSdbncokJlxRqE0LRmwaArp0R3UuV
"""

import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import glob
import os

file_paths = ['/JPM.csv', '/MSFT.csv', '/SNY.csv', '/VZ.csv', '/WBD.csv']
dataframes = []

for path in file_paths:
    df = pd.read_csv(path)
    df = df[['Date', 'close']]
    stock_name = os.path.splitext(os.path.basename(path))[0]
    df.rename(columns={'close': f'{stock_name}_close'}, inplace=True)
    dataframes.append(df)

# Merge on Date
merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = pd.merge(merged_df, df, on='Date')

merged_df['Date'] = pd.to_datetime(merged_df['Date'])
merged_df.sort_values('Date', inplace=True)
merged_df.reset_index(drop=True, inplace=True)
merged_df.dropna(inplace=True)  # remove rows with missing data

print(merged_df.head())

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(merged_df.drop('Date', axis=1))

SEQ_LEN = 20  # number of time steps in input
PRED_LEN = 1  # predict one step ahead

def create_sequences(data, seq_len=SEQ_LEN, pred_len=PRED_LEN):
    X, y = [], []
    for i in range(len(data) - seq_len - pred_len + 1):
        X.append(data[i:i+seq_len])
        y.append(data[i+seq_len:i+seq_len+pred_len, 0])  # Predict JPM only
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data)

X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)

#normalizes the stock data, then creates training sequences by sliding a window of SEQ_LEN (20) time steps
#and extracting the next time step's JPM closing price (column 0) as the target for each sequence.
#It then converts the resulting arrays into PyTorch tensors for model training.

class StockDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

dataset = StockDataset(X_tensor, y_tensor)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

#splitting to training and testing.
#X (past 20 days of prices) and labels y (next-day prices).
#80 20 split.

class TransformerModel(nn.Module):
    def __init__(self, input_dim, d_model=64, nhead=4, num_layers=2, dropout=0.1):
        super().__init__()
        self.embedding = nn.Linear(input_dim, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dropout=dropout)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.decoder = nn.Linear(d_model, 1)

    def forward(self, src):
        src = self.embedding(src)
        src = src.permute(1, 0, 2)
        output = self.transformer_encoder(src)
        out = self.decoder(output[-1])
        return out

#Transformer-based neural network model to predict the next stock price

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = TransformerModel(input_dim=X.shape[2]).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
loss_fn = nn.MSELoss()

EPOCHS = 30

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        output = model(X_batch)
        loss = loss_fn(output.squeeze(), y_batch.squeeze())
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss / len(train_loader):.5f}")

    #trains your Transformer model for 30 epochs

model.eval()
predictions, actuals = [], []

with torch.no_grad():
    for X_batch, y_batch in val_loader:
        X_batch = X_batch.to(device)
        pred = model(X_batch).cpu().numpy()
        predictions.extend(pred)
        actuals.extend(y_batch.numpy())

predictions = np.array(predictions).squeeze()
actuals = np.array(actuals).squeeze()

scaled_jpm = scaled_data[:, 0].reshape(-1, 1)
scaler_jpm = MinMaxScaler()
scaler_jpm.fit(scaled_jpm)

pred_real = scaler_jpm.inverse_transform(predictions.reshape(-1, 1))
actual_real = scaler_jpm.inverse_transform(actuals.reshape(-1, 1))

plt.figure(figsize=(10, 5))
plt.plot(pred_real, label='Predicted')
plt.plot(actual_real, label='Actual')
plt.legend()
plt.title('JPM Closing Price Prediction')
plt.show()

#evaluate trained model

tick = ['/JPM', '/MSFT', '/SNY', '/VZ', '/WBD']
dfs = []

for ticker in tick:
    df = pd.read_csv(f'{ticker}.csv')[['Date', 'close']]
    df.rename(columns={'close': f'{ticker}_close'}, inplace=True)
    dfs.append(df)

# Merge all on Date
data = dfs[0]
for df in dfs[1:]:
    data = pd.merge(data, df, on='Date')

data['Date'] = pd.to_datetime(data['Date'])
data.sort_values('Date', inplace=True)
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)

features = data.drop(columns=['Date']).values

scaler = MinMaxScaler()
scaled = scaler.fit_transform(features)

SEQ_LEN = 20  # history steps
PRED_LEN = 1  # 1-step ahead prediction

def create_sequences(data, seq_len, pred_len):
    X, y = [], []
    for i in range(len(data) - seq_len - pred_len + 1):
        X.append(data[i:i+seq_len])
        y.append(data[i+seq_len:i+seq_len+pred_len])
    return np.array(X), np.array(y)

X, y = create_sequences(scaled, SEQ_LEN, PRED_LEN)
y = y.squeeze(axis=1)  # shape: (samples, 5)

X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)

class StockDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

dataset = StockDataset(X_tensor, y_tensor)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

class MultiStockTransformer(nn.Module):
    def __init__(self, input_dim, d_model=64, nhead=4, num_layers=2, dropout=0.1, output_dim=5):
        super().__init__()
        self.embedding = nn.Linear(input_dim, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dropout=dropout)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.decoder = nn.Linear(d_model, output_dim)

    def forward(self, x):
        x = self.embedding(x)
        x = x.permute(1, 0, 2)  # [seq_len, batch, dim]
        encoded = self.transformer(x)
        out = self.decoder(encoded[-1])  # Use last token output
        return out

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MultiStockTransformer(input_dim=5, output_dim=5).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
loss_fn = nn.MSELoss()

EPOCHS = 30

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        pred = model(X_batch)
        loss = loss_fn(pred, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss / len(train_loader):.5f}")

model.eval()
preds, actuals = [], []

with torch.no_grad():
    for X_batch, y_batch in val_loader:
        X_batch = X_batch.to(device)
        output = model(X_batch).cpu().numpy()
        preds.append(output)
        actuals.append(y_batch.numpy())

preds = np.concatenate(preds)
actuals = np.concatenate(actuals)

# Inverse scale
preds_inv = scaler.inverse_transform(preds)
actuals_inv = scaler.inverse_transform(actuals)

# Plot for each stock
plt.figure(figsize=(14, 8))
for i, ticker in enumerate(tick):
    plt.subplot(3, 2, i+1)
    plt.plot(actuals_inv[:, i], label='Actual')
    plt.plot(preds_inv[:, i], label='Predicted')
    plt.title(f'{ticker} Closing Price')
    plt.legend()
plt.tight_layout()
plt.show()

#next 5 days
model.eval()


recent_sequence = torch.tensor(scaled[-SEQ_LEN:], dtype=torch.float32).unsqueeze(0).to(device)  # shape: [1, 20, 5]

future_predictions = []

with torch.no_grad():
    for _ in range(5):  # Predict next 5 days
        out = model(recent_sequence).squeeze(0)  # shape: [5]
        future_predictions.append(out.cpu().numpy())


        next_input = out.unsqueeze(0).unsqueeze(0).to(device)  # [1, 1, 5]
        recent_sequence = torch.cat([recent_sequence[:, 1:, :], next_input], dim=1)  # keep SEQ_LEN length


future_predictions = np.array(future_predictions)  # [5, 5]
future_real = scaler.inverse_transform(future_predictions)

# results
import datetime

last_date = data['Date'].iloc[-1]
next_dates = [last_date + datetime.timedelta(days=i+1) for i in range(5)]

forecast_df = pd.DataFrame(future_real, columns=[f'{t}_predicted' for t in tick])
forecast_df.insert(0, 'Date', next_dates)
print(forecast_df)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

import pandas as pd


jpm_df = pd.read_csv('JPM_with_price_diff.csv')
msft_df = pd.read_csv('MSFT_with_price_diff.csv')
sny_df = pd.read_csv('SNY_with_price_diff.csv')
vz_df = pd.read_csv('VZ_with_price_diff.csv')
wbd_df = pd.read_csv('WBD_with_price_diff.csv')

msft_sent_df = pd.read_csv('msft_sentiment_features_full.csv')
sny_sent_df = pd.read_csv('sny_sentiment_features_full.csv')
jpm_sent_df = pd.read_csv('v_sentiment_features_full.csv')  # verify if this is correct
vz_sent_df = pd.read_csv('vz_sentiment_features_full.csv')
wbd_sent_df = pd.read_csv('wbd_sentiment_features_full.csv')

from google.colab import files

uploaded = files.upload()

import pandas as pd


transcripts = {}


for filename in uploaded.keys():
    if filename.endswith('_transcript.csv'):
        df = pd.read_csv(filename)
        transcripts[filename] = df


print("Loaded Transcript Files:")
for name in transcripts:
    print(f"{name}: {transcripts[name].shape[0]} rows")

sentiment_files = {
    'MSFT': 'msft_sentiment_features_full.csv',
    'SNY': 'sny_sentiment_features_full.csv',
    'VZ': 'vz_sentiment_features_full.csv',
    'WBD': 'wbd_sentiment_features_full.csv',
    'JPM': 'v_sentiment_features_full.csv'
}

price_diff_files = {
    'MSFT': 'MSFT_with_price_diff.csv',
    'SNY': 'SNY_with_price_diff.csv',
    'VZ': 'VZ_with_price_diff.csv',
    'WBD': 'WBD_with_price_diff.csv',
    'JPM': 'JPM_with_price_diff.csv'
}

def load_and_merge(symbol):
    sent_df = pd.read_csv(sentiment_files[symbol])
    price_df = pd.read_csv(price_diff_files[symbol])


    sent_df['date'] = pd.to_datetime(sent_df['date'])
    price_df['Date'] = pd.to_datetime(price_df['Date'])

    merged = pd.merge(sent_df, price_df, left_on='date', right_on='Date')
    merged['symbol'] = symbol
    return merged


all_data = pd.concat([load_and_merge(sym) for sym in sentiment_files.keys()], ignore_index=True)

quantiles = all_data['Closing_price_change'].quantile([0.1, 0.9])
low_thresh = quantiles[0.1]
high_thresh = quantiles[0.9]

def classify(change):
    if change >= high_thresh:
        return 1  # Positive
    elif change <= low_thresh:
        return -1  # Negative
    else:
        return 0  # Neutral

all_data['label'] = all_data['Closing_price_change'].apply(classify)

print("All data shape:", all_data.shape)
print("Feature columns found in all_data:", [col for col in all_data.columns])

def load_and_merge(symbol):
    sent_df = pd.read_csv(sentiment_files[symbol])
    price_df = pd.read_csv(price_diff_files[symbol])

    sent_df['date'] = pd.to_datetime(sent_df['date']).dt.date
    price_df['Date'] = pd.to_datetime(price_df['Date']).dt.date


    merged = pd.merge(sent_df, price_df, left_on='date', right_on='Date', how='inner')
    merged['symbol'] = symbol
    return merged

all_data = pd.concat([load_and_merge(sym) for sym in sentiment_files.keys()], ignore_index=True)
print("Merged all_data shape:", all_data.shape)

# Only run this once!
quantiles = all_data['Closing_price_change'].quantile([0.1, 0.9])
low_thresh = quantiles[0.1]
high_thresh = quantiles[0.9]

def classify(change):
    if change >= high_thresh:
        return 1
    elif change <= low_thresh:
        return -1
    else:
        return 0

all_data['label'] = all_data['Closing_price_change'].apply(classify)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


feature_cols = ['sentiment_mean', 'sentiment_std', 'sentiment_count',
                'sentiment_min', 'sentiment_max', 'relevance_mean',
                'relevance_sum', 'overall_sentiment_mean',
                'overall_sentiment_std', 'source_count']

X = all_data[feature_cols]
y = all_data['label']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, stratify=y, random_state=42)

# multinomial logistic regression model
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, random_state=42)
clf.fit(X_train, y_train)

clf = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix


print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=["Negative (-1)", "Neutral (0)", "Positive (1)"]))

# Plot confusion matrix
conf_mat = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues',
            xticklabels=["Negative", "Neutral", "Positive"],
            yticklabels=["Negative", "Neutral", "Positive"])
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

# sort chronologically
all_data_sorted = all_data.sort_values(by='date')


X = all_data_sorted[feature_cols]
y = all_data_sorted['label']
X_scaled = scaler.fit_transform(X)

#Using TimeSeriesSplit for Accuracy.

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

tscv = TimeSeriesSplit(n_splits=5)

all_reports = []

for fold, (train_idx, test_idx) in enumerate(tscv.split(X_scaled)):
    print(f"\nFold {fold + 1}")

    X_train, X_test = X_scaled[train_idx], X_scaled[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    clf = LogisticRegression(
        multi_class='multinomial',
        solver='lbfgs',
        max_iter=1000,
        class_weight='balanced',
        random_state=42
    )

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)


    report = classification_report(y_test, y_pred, output_dict=True)
    all_reports.append(report)

    conf_mat = confusion_matrix(y_test, y_pred)
    sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues',
                xticklabels=["Negative", "Neutral", "Positive"],
                yticklabels=["Negative", "Neutral", "Positive"])
    plt.title(f"Confusion Matrix - Fold {fold + 1}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

# Average F1-score across all folds
avg_f1 = np.mean([fold['weighted avg']['f1-score'] for fold in all_reports])
print(f"\nAverage Weighted F1 Score Across Folds: {avg_f1:.4f}")

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


all_data_sorted = all_data.sort_values(by='date')


feature_cols = [
    'sentiment_mean', 'sentiment_std', 'sentiment_count',
    'sentiment_min', 'sentiment_max', 'relevance_mean',
    'relevance_sum', 'overall_sentiment_mean',
    'overall_sentiment_std', 'source_count'
]
X = all_data_sorted[feature_cols]
y = all_data_sorted['label']


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=5)
all_reports = []

for fold, (train_idx, test_idx) in enumerate(tscv.split(X_scaled)):
    X_train, X_test = X_scaled[train_idx], X_scaled[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]


    clf = RandomForestClassifier(
        n_estimators=100,
        class_weight='balanced',
        random_state=42
    )
    clf.fit(X_train, y_train)


    y_pred = clf.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    all_reports.append(report)


    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Negative', 'Neutral', 'Positive'],
                yticklabels=['Negative', 'Neutral', 'Positive'])
    plt.title(f'Confusion Matrix - Fold {fold+1}')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

# Average F1 Score
avg_f1 = np.mean([fold['weighted avg']['f1-score'] for fold in all_reports])
print(f"\nAverage Weighted F1 Score Across Folds: {avg_f1:.4f}")

